version: '3.8'

services:
  web:
    build: .
    expose:
      - "80"
    volumes:
      - ./www:/www
    environment:
      USER: ${USER}
      PASS: ${PASS}
    # all following settings are for traefik
    labels:
      - traefik.docker.network=web # your traefik network
      - traefik.enable=true
      - traefik.basic.frontend.rule=${HOST}
      - traefik.basic.port=80
      - traefik.basic.protocol=http
    networks:
      - web # your traefik network
networks:
  web: # your traefik network
    external: true